<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AxpoGroup.PowerPosition.Domain\AxpoGroup.PowerPosition.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PowerService">
      <HintPath>..\AxpoGroup.PowerPosition.Infrastructure\lib\PowerService.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
